--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: iso_messages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.iso_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    devise character varying(255),
    montant bigint,
    mti character varying(255),
    pan character varying(255),
    processing_code character varying(255),
    response_code character varying(255),
    rrn character varying(255),
    terminal_id character varying(255),
    transaction_date date,
    transaction_time time(6) without time zone
);


ALTER TABLE public.iso_messages OWNER TO admin;

--
-- Name: iso_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.iso_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iso_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: iso_messages iso_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.iso_messages
    ADD CONSTRAINT iso_messages_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

